import { LibroEntitie } from "./Entities/LibroEntities.model";
import { format } from "@formkit/tempo"

export const librosData: LibroEntitie[] = [
    {
      idLibro: 1,
      nombreLibro: 'Cien años de soledad',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial Sudamericana',
      idCategoria: 1,
      anioPublicacion: 1967,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 5,
    },
    {
      idLibro: 2,
      nombreLibro: 'Don Quijote de la Mancha',
      autorLibro: 'Miguel de Cervantes Saavedra',
      editorialLibro: 'Editorial EDAF',
      idCategoria: 1,
      anioPublicacion: 1605,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
    },
    {
      idLibro: 3,
      nombreLibro: '1984',
      autorLibro: 'George Orwell',
      editorialLibro: 'Editorial Secker & Warburg',
      idCategoria: 1,
      anioPublicacion: 1949,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
    },
    {
      idLibro: 4,
      nombreLibro: 'El principito',
      autorLibro: 'Antoine de Saint-Exupéry',
      editorialLibro: 'Editorial Reynal & Hitchcock',
      idCategoria: 1,
      anioPublicacion: 1943,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
    },
    {
      idLibro: 5,
      nombreLibro: 'Orgullo y prejuicio',
      autorLibro: 'Jane Austen',
      editorialLibro: 'Editorial Thomas Egerton',
      idCategoria: 1,
      anioPublicacion: 1813,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 1,
    },
    {
      idLibro: 6,
      nombreLibro: 'Ensayo sobre la ceguera',
      autorLibro: 'José Saramago',
      editorialLibro: 'Editorial Caminho',
      idCategoria: 1,
      anioPublicacion: 1995,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
    },
    {
      idLibro: 7,
      nombreLibro: 'El gran Gatsby',
      autorLibro: 'F. Scott Fitzgerald',
      editorialLibro: "Editorial Charles Scribner's Sons",
      idCategoria: 1,
      anioPublicacion: 1925,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
    },
    {
      idLibro: 8,
      nombreLibro: 'Matar a un ruiseñor',
      autorLibro: 'Harper Lee',
      editorialLibro: 'Editorial J. B. Lippincott & Co.',
      idCategoria: 1,
      anioPublicacion: 1960,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
    },
    {
      idLibro: 9,
      nombreLibro: 'Crimen y castigo',
      autorLibro: 'Fyodor Dostoevsky',
      editorialLibro: 'Editorial The Russian Messenger',
      idCategoria: 1,
      anioPublicacion: 1866,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
    },
    {
      idLibro: 10,
      nombreLibro: 'El señor de los anillos',
      autorLibro: 'J. R. R. Tolkien',
      editorialLibro: 'Editorial George Allen & Unwin',
      idCategoria: 1,
      anioPublicacion: 1954,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
    },
    {
      idLibro: 11,
      nombreLibro: 'Crónica de una muerte anunciada',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial La Oveja Negra',
      idCategoria: 1,
      anioPublicacion: 1981,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
    },
    {
      idLibro: 12,
      nombreLibro: 'El amor en los tiempos del cólera',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial Oveja Negra',
      idCategoria: 1,
      anioPublicacion: 1985,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
    },
    {
      idLibro: 13,
      nombreLibro: 'La sombra del viento',
      autorLibro: 'Carlos Ruiz Zafón',
      editorialLibro: 'Editorial Planeta',
      idCategoria: 1,
      anioPublicacion: 2001,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
    },
    {
      idLibro: 14,
      nombreLibro: 'El alquimista',
      autorLibro: 'Paulo Coelho',
      editorialLibro: 'Editorial Rocco',
      idCategoria: 1,
      anioPublicacion: 1988,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
    },
    {
      idLibro: 15,
      nombreLibro: 'Rayuela',
      autorLibro: 'Julio Cortázar',
      editorialLibro: 'Editorial Sudamericana',
      idCategoria: 1,
      anioPublicacion: 1963,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
    },
    {
      idLibro: 16,
      nombreLibro: 'Los pilares de la Tierra',
      autorLibro: 'Ken Follett',
      editorialLibro: 'Editorial Macmillan',
      idCategoria: 1,
      anioPublicacion: 1989,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
    },
    {
      idLibro: 17,
      nombreLibro: 'El código Da Vinci',
      autorLibro: 'Dan Brown',
      editorialLibro: 'Editorial Doubleday',
      idCategoria: 1,
      anioPublicacion: 2003,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
    },
  ];



  export const notificaciones: any[] =[
    {
      id: 1,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "El amor en los tiempos del cólera" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium")
    },
    {
      id: 2,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "La sombra del viento" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium")
    },
    {
      id: 3,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "El alquimista" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium")
    }
  ]