import { LibroEntitie } from "./Entities/LibroEntities.model";
import { format } from "@formkit/tempo"

export const librosData: LibroEntitie[] = [
    {
      idLibro: 1,
      nombreLibro: 'Cien años de soledad',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial Sudamericana',
      urlimage: 'https://p.calameoassets.com/220520111633-4a8dd3f15ae4b2249b9f303ba3254eea/p1.jpg',
      idCategoria: 1,
      anioPublicacion: 1967,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 5,
      esFavorito:false,
    },
    {
      idLibro: 2,
      nombreLibro: 'Don Quijote de la Mancha',
      autorLibro: 'Miguel de Cervantes Saavedra',
      editorialLibro: 'Editorial EDAF',
      urlimage:'https://www.capsulasliterarias.com/wp-content/uploads/2023/05/El-Ingenioso-Hidalgo-Don-Quijote-de-la-Mancha.png',
      idCategoria: 1,
      anioPublicacion: 1605,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
      esFavorito:false,
    },
    {
      idLibro: 3,
      nombreLibro: '1984',
      autorLibro: 'George Orwell',
      editorialLibro: 'Editorial Secker & Warburg',
      urlimage:'https://m.media-amazon.com/images/I/71sOSrd+JxL._AC_UF1000,1000_QL80_.jpg',
      idCategoria: 1,
      anioPublicacion: 1949,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
      esFavorito:false,
    },
    {
      idLibro: 4,
      nombreLibro: 'El principito',
      autorLibro: 'Antoine de Saint-Exupéry',
      editorialLibro: 'Editorial Reynal & Hitchcock',
      urlimage:'https://www.brunolibros.es/images/libros/grande/9788469668849-el-principito-y-las-estrellas-el-principito.jpg',
      idCategoria: 1,
      anioPublicacion: 1943,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 0,
      esFavorito:false,
    },
    {
      idLibro: 5,
      nombreLibro: 'Orgullo y prejuicio',
      autorLibro: 'Jane Austen',
      editorialLibro: 'Editorial Thomas Egerton',
      urlimage:'https://i0.wp.com/www.cinemanet.info/wp-content/uploads/2012/12/orgulloprejuicio_frontal-210x300.jpg?resize=200%2C300',
      idCategoria: 1,
      anioPublicacion: 1813,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 1,
      esFavorito:false,
    },
    {
      idLibro: 6,
      nombreLibro: 'Ensayo sobre la ceguera',
      autorLibro: 'José Saramago',
      editorialLibro: 'Editorial Caminho',
      urlimage:'https://m.media-amazon.com/images/I/717ZqBXBF9L._AC_UF1000,1000_QL80_.jpg',
      idCategoria: 1,
      anioPublicacion: 1995,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
      esFavorito:false,
    },
    {
      idLibro: 7,
      nombreLibro: 'El gran Gatsby',
      autorLibro: 'F. Scott Fitzgerald',
      editorialLibro: "Editorial Charles Scribner's Sons",
      urlimage:'https://www.anagrama-ed.es/uploads/media/portadas/0001/15/b2834bc4ea71357c8b549dfccdd16d611c6586ea.jpeg',
      idCategoria: 1,
      anioPublicacion: 1925,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
      esFavorito:false,
    },
    {
      idLibro: 8,
      nombreLibro: 'Matar a un ruiseñor',
      autorLibro: 'Harper Lee',
      editorialLibro: 'Editorial J. B. Lippincott & Co.',
      urlimage:'https://contrapunto.cl/22071/matar-un-ruisenor.jpg',
      idCategoria: 1,
      anioPublicacion: 1960,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
      esFavorito:false,
    },
    {
      idLibro: 9,
      nombreLibro: 'Crimen y castigo',
      autorLibro: 'Fyodor Dostoevsky',
      editorialLibro: 'Editorial The Russian Messenger',
      urlimage:'https://hispamer.com.ni/wp-content/uploads/2022/06/9788418008122-1.jpg',
      idCategoria: 1,
      anioPublicacion: 1866,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
      esFavorito:false,
    },
    {
      idLibro: 10,
      nombreLibro: 'El señor de los anillos',
      autorLibro: 'J. R. R. Tolkien',
      editorialLibro: 'Editorial George Allen & Unwin',
      urlimage:'https://pics.filmaffinity.com/El_seanor_de_los_anillos_La_comunidad_del_anillo-744631610-large.jpg',
      idCategoria: 1,
      anioPublicacion: 1954,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
      esFavorito:false,
    },
    {
      idLibro: 11,
      nombreLibro: 'Crónica de una muerte anunciada',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial La Oveja Negra',
      urlimage:'https://m.media-amazon.com/images/I/91geyJSGR6L._AC_UF894,1000_QL80_.jpg',
      idCategoria: 1,
      anioPublicacion: 1981,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
      esFavorito:false,
    },
    {
      idLibro: 12,
      nombreLibro: 'El amor en los tiempos del cólera',
      autorLibro: 'Gabriel Garcia Marquez',
      editorialLibro: 'Editorial Oveja Negra',
      urlimage:'https://hispamer.com.ni/wp-content/uploads/2023/02/9786070729164.jpg',
      idCategoria: 1,
      anioPublicacion: 1985,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
      esFavorito:false,
    },
    {
      idLibro: 13,
      nombreLibro: 'La sombra del viento',
      autorLibro: 'Carlos Ruiz Zafón',
      editorialLibro: 'Editorial Planeta',
      urlimage:'https://hispamer.com.ni/wp-content/uploads/2022/05/9786070721632.jpg',
      idCategoria: 1,
      anioPublicacion: 2001,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
      esFavorito:false,
    },
    {
      idLibro: 14,
      nombreLibro: 'El alquimista',
      autorLibro: 'Paulo Coelho',
      editorialLibro: 'Editorial Rocco',
      urlimage:'https://hispamer.com.ni/wp-content/uploads/2023/01/9786073158602.jpg',
      idCategoria: 1,
      anioPublicacion: 1988,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
      esFavorito:false,
    },
    {
      idLibro: 15,
      nombreLibro: 'Rayuela',
      autorLibro: 'Julio Cortázar',
      editorialLibro: 'Editorial Sudamericana',
      urlimage:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Rayuela_JC.png/640px-Rayuela_JC.png',
      idCategoria: 1,
      anioPublicacion: 1963,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 3,
      esFavorito:false,
    },
    {
      idLibro: 16,
      nombreLibro: 'Los pilares de la Tierra',
      autorLibro: 'Ken Follett',
      editorialLibro: 'Editorial Macmillan',
      urlimage:'https://m.media-amazon.com/images/I/91G5zRD4wDL._AC_UF1000,1000_QL80_.jpg',
      idCategoria: 1,
      anioPublicacion: 1989,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 4,
      esFavorito:false,
    },
    {
      idLibro: 17,
      nombreLibro: 'El código Da Vinci',
      autorLibro: 'Dan Brown',
      editorialLibro: 'Editorial Doubleday',
      urlimage:'https://m.media-amazon.com/images/I/71PR0C4XNjL._AC_UF1000,1000_QL80_.jpg',
      idCategoria: 1,
      anioPublicacion: 2003,
      nombreCategoria: 'Novela',
      ejemplaresDisponible: 2,
      esFavorito:false,
    },
  ];



  export const notificaciones: any[] =[
    {
      id: 1,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "El amor en los tiempos del cólera" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium"),
      leida: false
    },
    {
      id: 2,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "La sombra del viento" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium"),
      leida: false
    },
    {
      id: 3,
      titulo: 'Nuevo libro disponible',
      mensaje: 'El libro "El alquimista" ya está disponible para su préstamo',
      fecha: format(new Date(), "medium"),
      leida: false
    }
  ]